# Generated by Django 4.2.15 on 2025-09-06 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nexapp_users", "0021_rename_user_id_email_openwisp_us_id_06c07a_idx"),
        ("firmware_upgrader", "0011_alter_category_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="nexapp_users.organization",
                verbose_name="organization",
            ),
        ),
    ]
