# Generated by Django 5.2.6 on 2025-09-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firmware_upgrader", "0012_alter_category_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="upgradeoperation",
            name="progress",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Progress percentage (0–100) of the upgrade process",
            ),
        ),
    ]
