# Generated by Django 5.2.6 on 2025-09-18 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("firmware_upgrader", "0013_upgradeoperation_progress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="upgradeoperation",
            name="progress",
        ),
    ]
