# Generated by Django 4.2.16 on 2026-01-14 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("firmware_upgrader", "0014_remove_upgradeoperation_progress"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceFirmwareSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("scheduled", "scheduled"),
                            ("running", "running"),
                            ("success", "success"),
                            ("failed", "failed"),
                            ("canceled", "canceled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device_firmware",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to=settings.FIRMWARE_UPGRADER_DEVICEFIRMWARE_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Firmware Schedule",
                "verbose_name_plural": "Device Firmware Schedules",
                "abstract": False,
                "swappable": "FIRMWARE_UPGRADER_DEVICEFIRMWARESCHEDULE_MODEL",
            },
        ),
    ]
