# Generated by Django 4.2.16 on 2026-01-23 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("firmware_upgrader", "0015_devicefirmwareschedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upgradeoperation",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "scheduled"),
                    ("in-progress", "in progress"),
                    ("success", "success"),
                    ("failed", "failed"),
                    ("aborted", "aborted"),
                ],
                default="scheduled",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="BatchUpgradeOperationSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("scheduled", "scheduled"),
                            ("running", "running"),
                            ("success", "success"),
                            ("failed", "failed"),
                            ("canceled", "canceled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "batch_operation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to=settings.FIRMWARE_UPGRADER_BATCHUPGRADEOPERATION_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch Upgrade Operation Schedule",
                "verbose_name_plural": "Batch Upgrade Operation Schedules",
                "abstract": False,
                "swappable": "FIRMWARE_UPGRADER_BATCHUPGRADEOPERATIONSCHEDULE_MODEL",
            },
        ),
    ]
