# Generated by Django 4.2.16 on 2026-01-31 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.CONFIG_DEVICE_MODEL),
        ("firmware_upgrader", "0016_alter_upgradeoperation_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="devices",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select the devices included in this category for mass upgrade.",
                related_name="firmware_categories",
                to=settings.CONFIG_DEVICE_MODEL,
                verbose_name="Devices",
            ),
        ),
        migrations.AlterField(
            model_name="batchupgradeoperation",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "scheduled"),
                    ("in-progress", "in progress"),
                    ("success", "completed successfully"),
                    ("failed", "completed with some failures"),
                ],
                default="scheduled",
                max_length=12,
            ),
        ),
    ]
