# Generated by Django 4.2.15 on 2026-04-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware_upgrader', '0017_category_devices_alter_batchupgradeoperation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='upgrade_type',
            field=models.CharField(choices=[('full_image', 'Full Image (sysupgrade)'), ('ipk_package', 'Package Patch (.ipk)')], default='full_image', help_text='Full Image: replaces entire firmware via sysupgrade. Package Patch: installs .ipk package via opkg (no reboot).', max_length=16, verbose_name='upgrade type'),
        ),
    ]
