# Generated by Django 4.2.15 on 2026-04-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware_upgrader', '0018_add_build_upgrade_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='upgrade_type',
            field=models.CharField(choices=[('full_image', 'Full Image'), ('ipk_package', 'Package Patch')], default='full_image', help_text='Full Image: replaces entire firmware. Package Patch: installs a software package (no reboot required).', max_length=16, verbose_name='upgrade type'),
        ),
    ]
